# Generated by Django 3.2.8 on 2021-10-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_brands_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerad',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sliderad',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='bannerad',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
