# Generated by Django 3.2.8 on 2021-11-02 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='slug',
        ),
    ]
