# Generated by Django 3.2.8 on 2021-11-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_value',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
